import Link from "next/link";
import { CopyValue } from "./CopyValue";
import { usd } from "@/lib/format";

/**
 * Explains where refund money comes from. Deliberately says "creator fees from
 * trading volume", not "trading volume" — volume is turnover between traders,
 * not income, and promising it outright would be a promise nobody can keep.
 */
export function RefundPool({ poolWallet, refunded }: { poolWallet: string; refunded: number }) {
  return (
    <section className="section">
      <div className="section-head">
        <h2 className="section-title">The refund pool</h2>
        <span className="section-note">
          {refunded > 0 ? `${usd(refunded)} returned so far` : "funded by $MGM trading"}
        </span>
      </div>

      <div className="pool">
        <div>
          <h3>
            Every fee $MGM earns goes back to <em>the people who got rugged.</em>
          </h3>
          <p>
            MGM does not take a cut of anyone&apos;s recovery. The token is the funding
            mechanism: <strong style={{ color: "var(--text-primary)" }}>100% of the creator fees
            generated by $MGM trading volume</strong> is paid into the refund pool, and the pool
            pays out to the wallets attached to verified claims.
          </p>
          <p>
            Every claim is signed by the wallet that took the loss, so a payout can only ever reach
            the person who actually filed it — never a stranger holding someone else&apos;s screenshot.
          </p>
          <div className="pool-wallet">
            <span className="k">Pool wallet · fees in, refunds out</span>
            <CopyValue value={poolWallet} />
          </div>

          <p style={{ marginTop: "var(--space-5)" }}>
            <Link className="btn btn-ghost" href="/how-it-works#pool">How payouts work ›</Link>
          </p>
        </div>

        <div className="pool-flow">
          <div className="pool-step">
            <span className="n">1</span>
            <span>
              <span className="t">You trade $MGM</span>
              <span className="d">Every buy and sell generates a creator fee on the launchpad.</span>
            </span>
          </div>
          <div className="pool-step">
            <span className="n">2</span>
            <span>
              <span className="t">Fees collect in the pool</span>
              <span className="d">Not revenue, not a treasury — earmarked for payouts only.</span>
            </span>
          </div>
          <div className="pool-step is-last">
            <span className="n">3</span>
            <span>
              <span className="t">Verified claims get paid</span>
              <span className="d">Straight to the wallet that signed the claim. Amount recorded on the case.</span>
            </span>
          </div>
        </div>
      </div>
    </section>
  );
}
